### ISSUE TITLE
mysql port

### ISSUE THREAD

**Issue by palansher** [michalhosna/adminer-docker#7]
Thank you for great job!

No possibility to set non-standard port for mysql/mariadb ?

**Comment by michalhosna** [comment]
You can set non-standart port for mysql/mariadb as for any other db type in the `ADMINER_SERVER` env var, e.g. `            ADMINER_SERVER: mysql:61894`. 

Please try that and let me known if it works for you :) 

## Full example:

`port.cnf`
```
[mysqld]
port=61894
```
`docker-compose.yaml`
```yaml
version: '2.4'
services:
    adminer:
        image: michalhosna/adminer:4.8.1-en_v1
        ports:
            - 8080:8080
        environment:           
            ADMINER_SERVER: mysql-server:61894
            ADMINER_DB: mysql
            ADMINER_PASSWORD: adminer
            ADMINER_USERNAME: root
            ADMINER_AUTOLOGIN: 1
            ADMINER_NAME: This will be in the title!

    mysql-server:
        image: mysql:8-debian
        platform: linux/amd64
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ./port.cnf:/etc/mysql/conf.d/port.cnf
        environment:
            MYSQL_ROOT_PASSWORD: adminer
```

Sorry for late reply
