### ISSUE TITLE
Add support for `ADMINER_DESIGN` variable

### ISSUE THREAD

**Issue by mbalc** [michalhosna/adminer-docker#8]
`ADMINER_DESIGN` environment variable, which works in the official Docker adminer image, does not work with this Docker image

https://hub.docker.com/_/adminer#choosing_a_design

**Comment by felipeolliveira** [comment]
I created my own `Dockerfile` from @michalhosna image:

```dockerfile
FROM michalhosna/adminer

USER root

ARG ADMINER_DESIGN="nette"

WORKDIR /var/adminer
RUN echo "Getting design for Adminer: ${ADMINER_DESIGN}..."
RUN curl -L https://raw.githubusercontent.com/vrana/adminer/master/designs/${ADMINER_DESIGN}/adminer.css -o adminer.css
```

So you can run in container from a compose file...
```yaml
# ...
services:
  adminer:
    build:
      context: "path/to/dockerfile"
      args:
        - ADMINER_DESIGN=dracula
# ...
```
Or build with `docker run`:
```sh
docker build -t adminer-auto-signin-with-theme .
docker run -d -p 8080:8080 adminer-auto-signin-with-theme 
```

![image](https://github.com/michalhosna/adminer-docker/assets/19709577/a987a07f-4f26-4dcb-ad88-b93c475735ee)

🖖🏼
